config/routes.rb
Rails.application.routes.draw do
 resources :blogs, only: [:index, :new, :create, :edit, :update ,:destroy] do
    collection do
      post :confirm
    end
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
    validates :title, presence: true
    validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy]
  
  def index
    @blogs = Blog.all
  end
  
  def new
    @blog = Blog.new
  end
  
  def create
    @blog = Blog.new(blogs_params)
    if @blog.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      # 入力フォームを再描画します。
      render action: 'new'
    end
  end
  

  def edit
    # edit, update, destroyで共通コード
    #@blog = Blog.find(params[:id])
  end

  def update
    # edit, update, destroyで共通コード
   # @blog = Blog.find(params[:id])

    if @blog.update(blogs_params)
      redirect_to blogs_path, notice: "ブログを更新しました！"
    else
      render action: 'edit'
    end
  end

  def destroy
    # edit, update, destroyで共通コード
    #@blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice: "ブログを削除しました！"
  end

  private
    def blogs_params
      params.require(:blog).permit(:title, :content)
    end
    
     # idをキーとして値を取得するメソッド
    def set_blog
      @blog = Blog.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    module BlogsHelper
     def choose_new_or_edit
         if action_name == 'new' || action_name == 'confirm'
         confirm_blogs_path
         elsif action_name == 'edit'
         blog_path
        end
     end
    end
end

app/views/blogs/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      # バリデーションエラーの件数を表示します。
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>

      <ul>
      # @blog.errosは@blogをバリデーションした際のエラー情報です。
      # full_messagesは複数のエラーメッセージを表します。
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <br>
  <%= f.submit %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_for(@blog) do |f| %>
  <!-- `f.hidden_field`を使用して、リクエストパラメータに値を設定できるようにしています。 -->
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>

  <!-- @blog.titleと@blog.contentとすることで、表示用の値を画面に出力しています。 -->
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= f.submit "登録する" %>
<% end %>

app/views/blogs/index.html.1.erb
<h1>Blogs#index</h1>
<p>Find me in app/views/blogs/index.html.erb</p>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<% @blogs.each do |blog| %>
  <p>タイトル:<%= blog.title %></p>
  <p>本文:<%= blog.content %></p>
  <%= link_to "ブログを編集する", edit_blog_path(blog.id) %>
<% end %>

app/views/blogs/new.html.erb
<h2>ブログを作成する</h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Achieve04</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>